feat(#14): 2FA
bitbit-Merry-go-round/Transcendence-BE pull request #49
Opened 2024-04-04 12:49 UTC by hyemch

## 📌 연관된 이슈
- #14 

## 📝 작업 내용
- 사용자 계정 보안을 위한 추가적인 2단계 인증 기능 구현
  - 42 API를 통해 가져온 사용자의 42 email로 otp 코드 전송
  - 사용자가 입력한 otp 코드와 전송한 otp 코드가 일치하는지 확인

## 🌳 작업 브랜치명
`feat/2fa`

## 📸 스크린샷 (선택)
<img width="582" alt="스크린샷 2024-04-04 오후 9 48 27" src="https://github.com/bitbit-Merry-go-round/Transcendence-BE/assets/102580205/41c564b6-ef1a-452f-b04d-951bd7d9766d">

## 💬 리뷰 요구사항 (선택)

2024-04-04 13:56 UTC, ohhamma requested changes
코드를 받아서 돌려봤더니 올바른 OTP 코드를 입력했음에도 불구하고 POST 오류가 발생합니다.
수정 부탁드립니다!

![otp-error](https://github.com/bitbit-Merry-go-round/Transcendence-BE/assets/81293930/92074dae-1983-4f69-a388-61ae0e9631c8)

2024-04-04 13:58 UTC, hyemch commented
> 코드를 받아서 돌려봤더니 올바른 OTP 코드를 입력했음에도 불구하고 POST 오류가 발생합니다.
> 
> 수정 부탁드립니다!
> 
> 
> 
> ![otp-error](https://github.com/bitbit-Merry-go-round/Transcendence-BE/assets/81293930/92074dae-1983-4f69-a388-61ae0e9631c8)
> 
> 

프론트 코드도 pull 하셨나요?!

2024-04-04 14:00 UTC, ohhamma commented
그리고 `add-user.py` 파일에서 더미 유저를 생성할 때 이메일 값도 같이 넣어주세요!
```python
user = User(username="jeseo", email="jeseo@student.42seoul.kr")
```

2024-04-04 14:01 UTC, ohhamma commented
프론트 코드도 pull 했습니다! `feat/2fa` 브랜치를 말씀하시는게 맞을까요?

2024-04-04 14:01 UTC, ohhamma commented
> 프론트 코드도 pull 하셨나요?!

프론트 코드도 pull 했습니다! feat/2fa 브랜치를 말씀하시는게 맞을까요?

2024-04-04 14:07 UTC, hyemch commented
넵 feat/2fa 브랜치이고, 각자 다른 환경에사 테스트할때 정상작동해서 올렸는데 둘다 잘 받아와서 테스트해보신거라면 다시 확인해보겠습니다~

2024-04-04 14:09 UTC, ohhamma commented
네 좋습니다! 내일 같이 해결해보아요 🙂

2024-04-04 14:12 UTC, hyemch commented
최대한 빠르게 확인해보겠습니다~~~!

2024-04-04 15:29 UTC, hyemch commented
테스트 다시 해본 결과, 저는 정상적으로 잘 작동하였습니다. 다만 로그아웃을 하거나 액세스 토큰이 만료된 후에도 로컬 스토리지에 그대로 남아있는 것을 확인하였고, 각기 브라우저 환경이 달라 에러가 발생하는 것 같습니다! 로컬 스토리지에 있는 토큰을 삭제해주고 다시 테스트 부탁드립니다!😊

2024-04-08 06:23 UTC, ohhamma commented
확인이 늦어 죄송합니다. 말씀해주신 대로 로컬 스토리지에 저장되어 있던 토큰을 삭제하고 실행해보니 잘 되는 것을 확인했습니다. 수고하셨습니다!

2024-04-08 06:24 UTC, ohhamma approved these changes
확인이 늦어 죄송합니다. 말씀해주신 대로 로컬 스토리지에 저장되어 있던 토큰을 삭제하고 실행해보니 잘 되는 것을 확인했습니다. 수고하셨습니다!

2024-04-08 06:24 UTC, merged